prSections:
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Dependabot
    filters: is:pr is:open author:app/dependabot
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 20
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
        hidden: true
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  # https://github.com/dlvhdr/gh-dash#%EF%B8%8F-keybindings
  issues: []
  prs:
    # Approve and Merge
    - key: M
      command: |
        (gh pr review {{.PrNumber}} --repo {{.RepoName}} --approve
        if ! gh pr merge {{.PrNumber}} --repo {{.RepoName}} --squash; then
          echo "Failed to merge PR #{{.PrNumber}} in {{.RepoName}}"
          exit 1
        fi) > /dev/null &
pager:
  diff: ""
theme:
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#f5c2e7"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f9e2af"
      success: "#a6e3a1"
      error: "#f38ba8"
    background:
      selected: "#313244"
    border:
      primary: "#f5c2e7"
      secondary: "#45475a"
      faint: "#313244"
